---
- name: local install
  hosts: all
  connection: local
  become: yes
  become_method: sudo

  roles:
    - packages
    - network
    - locales
    - nfs
    - account
    - docker
    - postfix
    - gitlab-runner
    - vagrant-tools
