---
- name: local install
  hosts: all
  connection: local
  become: yes
  become_method: sudo
  vars:
    docker_allowed_user:
      - vagrant

    apt_upgrade: true
    apt_extra_packages:
      - dos2unix
      - vim-doc
      - trash-cli
      - mc
      - manpages-fr
      - manpages-fr-dev
      - manpages-fr-extra
      - git-extras
      - git-doc
      - nfs-common
      - portmap

  roles:
    - docker
